// src/modules/Dashboard/components/Header/Search.vue
<template>
  <label class="search-input__container">
    <SearchIcon />
    <input type="text" placeholder="Search"/>
  </label>
</template>

<script>
import SearchIcon from "./Icons/SearchIcon.vue";

export default {
  name: "Search",

  components: {
    SearchIcon
  }
}
</script>

<style>
@import "../../assets/search.scss";
</style>

// src/modules/Dashboard/components/Header/Search.tsx
import React, {FC} from 'react';
import SearchIcon from "modules/Dashboard/components/Header/Icons/SearchIcon";
import "modules/Dashboard/assets/search.scss";

const Search: FC = () => {
  return (
    <label className="search-input__container">
      <SearchIcon />
      <input type="text" placeholder="Search"/>
    </label>
  );
}

export default Search;
