// src/modules/Dashboard/components/Recent/CardsBlock.vue
<template>
  <div class="cards-block__container">
    <h3>{{title}}</h3>

    <div class="cards-block__list">
      <template v-if="props.cards.length === 0">
        <v-skeleton-loader
          v-for="n in 3"
          :key="n"
          max-width="250"
          width="250"
          type="image"
        >
        </v-skeleton-loader>
      </template>

      <router-link v-for="(card, i) in props.cards" :to="`/p/${card.codeName}`"
                   :key="i"
                   class="cards-block__card">
        <header class="card__header">
          <h4>{{card.name}}</h4>
<!--          <CardMenu />-->
        </header>
        <footer class="card__footer">
          <time>{{getLastUpdate(card.updatedAt)}}</time>
        </footer>
      </router-link>
    </div>
  </div>
</template>

<script setup lang="ts">
import {formatRelative} from "date-fns";
import { ru } from 'date-fns/locale'
import {defineProps} from "vue";

const props = defineProps(['title', 'cards']);

function getLastUpdate(date) {
  return formatRelative(date, new Date(), { locale: ru })
}
</script>

// src/modules/Dashboard/components/Recent/CardsBlock.tsx
import React, {FC} from 'react';
import {Link} from "react-router-dom";
import CardMenu from "modules/Dashboard/components/Recent/CardMenu";

// TODO: Type for card
interface ICardsBlock {
  title: string,
  cards: Array<any>
}

const CardsBlock: FC<ICardsBlock> = (props) => {
  const {title, cards} = props;

  return (
    <div className="cards-block__container">
      <h3>{title}</h3>

      <div className="cards-block__list">
        {cards.map((card, i) => (
          <Link to={`/p/${card.name}`} className="cards-block__card">
            <header className="card__header">
              <h4>{card.name}</h4>
              <CardMenu />
            </header>
            <footer className="card__footer">
              <time>{card.lastUpdate}</time>
            </footer>
          </Link>
        ))}
      </div>
    </div>
  );
}

export default CardsBlock;
