// src/modules/Dashboard/components/Recent/Recent.tsx
import React, {FC} from 'react';
import Button from "components/Button";
import {Size, Variant} from "utils/types/global.types";
import "modules/Dashboard/assets/recent.scss";
import ProjectsIcon
  from "modules/Dashboard/components/Sidebar/Icons/ProjectsIcon";
import PlusIcon from "modules/Dashboard/components/Header/Icons/PlusIcon";
import ImportIcon from "modules/Dashboard/components/Recent/Icons/ImportIcon";
import CardsBlock from "modules/Dashboard/components/Recent/CardsBlock";

const cards = [
  {
    name: "test-project-rxgsl",
    lastUpdate: "2d ago",
  },
  {
    name: "test-project-rxgsl",
    lastUpdate: "2d ago",
  },
  {
    name: "test-project-rxgsl",
    lastUpdate: "2d ago",
  },
  {
    name: "test-project-rxgsl",
    lastUpdate: "2d ago",
  },
  {
    name: "test-project-rxgsl",
    lastUpdate: "2d ago",
  },
  {
    name: "test-project-rxgsl",
    lastUpdate: "2d ago",
  },
];

const Recent: FC = () => {
  return (
    <div className="recent__container">
      <h2>Recent</h2>

      <div className="recent__actions">
        <Button variant={Variant.Contained} size={Size.Large}>
          <ProjectsIcon />
          <span>New project</span>
        </Button>
        <Button variant={Variant.Contained} size={Size.Large}>
          <ImportIcon />
          <span>Import repository</span>
        </Button>
        <Button variant={Variant.Contained} size={Size.Large}>
          <PlusIcon />
          <span>Create team</span>
        </Button>
      </div>

      <CardsBlock title="Pick up where you left off" cards={cards} />
      <CardsBlock title="Pick up where you left off" cards={cards} />
    </div>
  );
}

export default Recent;

// src/modules/Dashboard/components/Recent/Recent.vue
<template>
  <div class="recent__container">
    <h2>Недавние</h2>

    <div class="recent__actions">
      <ButtonComponent @click="() => createDialog = true"
                       :variant="Variant.Contained"
                       :size="Size.Large">
        <ProjectsIcon />
        <span>Новый проект</span>
      </ButtonComponent>
      <ButtonComponent :variant="Variant.Contained" :size="Size.Large">
        <ImportIcon />
        <span>Импорт репозитория</span>
      </ButtonComponent>
      <ButtonComponent :variant="Variant.Contained" :size="Size.Large">
        <PlusIcon />
        <span>Создать команду</span>
      </ButtonComponent>
    </div>

    <CreateProjectModal :show="createDialog"
                        @closeDialog="createDialog = false"
                        @projectCreated="updateRecentProjects" />

    <CardsBlock title="Вы недавно открывали" :cards="cards" />
  </div>
</template>

<script setup lang="ts">
import ButtonComponent from "@/components/ButtonComponent.vue";
import PlusIcon from "../Header/Icons/PlusIcon.vue";
import ImportIcon from "./Icons/ImportIcon.vue";
import ProjectsIcon from "./Icons/ProjectsIcon.vue";
import CardsBlock from "./CardsBlock.vue";
import {Size, Variant} from "@/utils/types/global.types";
import {onBeforeMount, reactive, ref} from "vue";
import CreateProjectModal
  from "@/modules/Dashboard/components/CreateProjectModal.vue";
import {getRecentProjects} from "@/utils/services/projects.service";

const createDialog = ref<Boolean>(false);
const page = ref<number>(1);
const cards = ref([]);

onBeforeMount(async () => {
  cards.value = await getRecentProjects(page.value);
});

async function updateRecentProjects() {
  cards.value = await getRecentProjects(page.value);
}
</script>

<style>
@import "../../assets/recent.scss";
</style>
