// src/components/Button.tsx
import React, {FC} from 'react';
import {
  IButton,
  Size,
  Variant
} from "utils/types/global.types";

const Button: FC<IButton> = ({children, variant = Variant.Text, size = Size.Medium, onClick= () => {}}) => {
  const classes = `${variant} ${size}`;

    return (
      <button className={classes} onClick={onClick}>
        {children}
      </button>
    );
}

export default Button;

// src/components/ButtonComponent.vue
<template>
  <button :class="classes">
    <slot />
  </button>
</template>

<script lang="ts">
import { Size, Variant } from "@/utils/types/global.types";

export default {
  name: "ButtonComponent",

  props: {
    variant: {
      type: String,
      default: Variant.Text
    },
    size: {
      type: String,
      default: Size.Medium
    }
  },

  computed: {
    classes() {
      return `${this.variant} ${this.size} ${this.$attrs.class}`
    }
  }
}
</script>
